# Generated by Django 5.0.4 on 2024-05-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0004_department_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='department',
            name='cars',
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DepartmentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sto.department')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sto.cars')),
            ],
            options={
                'unique_together': {('department', 'cars')},
            },
        ),
    ]
