# Generated by Django 5.0.4 on 2024-05-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0005_remove_department_amount_remove_department_cars_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentCar',
        ),
    ]
